# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDH629j9gKSGTnLiN3vhwAjrYKpsTynT
"""

lfrom google.colab import files
upload=files.upload()
import pandas as pd
import numpy as np
dataset=pd.read_csv("datatest.csv")

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
iris=pd.read_csv("datatest.csv")
plt.figure(figsize=(10,6))
sns.scatterplot(data=dataset,x="Temperature",y="Humidity",hue="CO2",palette="Spectral")
plt.title("Teperature vs Humidity")
plt.xlabel("Temperature")
plt.ylabel("Humidity")
plt.legend(title="CO2")
plt.show()

import pandas as pd
import seaborn as sd
import matplotlib.pyplot as plt
iris=pd.read_csv("datatest.csv")
plt.figure(figsize=(9,4))
sd.lineplot(data=iris,x="Temperature",y="Humidity",hue="CO2",marker="o")
plt.title("Temperature vs Humidity")
plt.xlabel("Temperature")
plt.ylabel("Humidity")
plt.grid(True)
plt.show()

numeric_columns=dataset.select_dtypes(include=['float64','int64'])
corr_matrix=numeric_columns.corr()
print(corr_matrix)
plt.figure(figsize=(5,3))
sns.heatmap(corr_matrix,annot=True,cmap="Spectral",fmt=".2f")
plt.title("CORRELATIN MAP OF Datatest DATASET")
plt.show()